import React, { useState, useRef, useEffect } from "react";
import "./PhoneInput.css";

// Full country list: { code, dialCode, flag, minLen, maxLen }
const COUNTRIES = [
  {
    code: "PK",
    name: "Pakistan",
    dialCode: "+92",
    flag: "🇵🇰",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "AF",
    name: "Afghanistan",
    dialCode: "+93",
    flag: "🇦🇫",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "AL",
    name: "Albania",
    dialCode: "+355",
    flag: "🇦🇱",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "DZ",
    name: "Algeria",
    dialCode: "+213",
    flag: "🇩🇿",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "AD",
    name: "Andorra",
    dialCode: "+376",
    flag: "🇦🇩",
    minLen: 6,
    maxLen: 9,
  },
  {
    code: "AO",
    name: "Angola",
    dialCode: "+244",
    flag: "🇦🇴",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    dialCode: "+1268",
    flag: "🇦🇬",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "AR",
    name: "Argentina",
    dialCode: "+54",
    flag: "🇦🇷",
    minLen: 10,
    maxLen: 11,
  },
  {
    code: "AM",
    name: "Armenia",
    dialCode: "+374",
    flag: "🇦🇲",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "AU",
    name: "Australia",
    dialCode: "+61",
    flag: "🇦🇺",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "AT",
    name: "Austria",
    dialCode: "+43",
    flag: "🇦🇹",
    minLen: 7,
    maxLen: 13,
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    dialCode: "+994",
    flag: "🇦🇿",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "BS",
    name: "Bahamas",
    dialCode: "+1242",
    flag: "🇧🇸",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "BH",
    name: "Bahrain",
    dialCode: "+973",
    flag: "🇧🇭",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "BD",
    name: "Bangladesh",
    dialCode: "+880",
    flag: "🇧🇩",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "BB",
    name: "Barbados",
    dialCode: "+1246",
    flag: "🇧🇧",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "BY",
    name: "Belarus",
    dialCode: "+375",
    flag: "🇧🇾",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "BE",
    name: "Belgium",
    dialCode: "+32",
    flag: "🇧🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "BZ",
    name: "Belize",
    dialCode: "+501",
    flag: "🇧🇿",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "BJ",
    name: "Benin",
    dialCode: "+229",
    flag: "🇧🇯",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "BT",
    name: "Bhutan",
    dialCode: "+975",
    flag: "🇧🇹",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "BO",
    name: "Bolivia",
    dialCode: "+591",
    flag: "🇧🇴",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    dialCode: "+387",
    flag: "🇧🇦",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "BW",
    name: "Botswana",
    dialCode: "+267",
    flag: "🇧🇼",
    minLen: 7,
    maxLen: 8,
  },
  {
    code: "BR",
    name: "Brazil",
    dialCode: "+55",
    flag: "🇧🇷",
    minLen: 10,
    maxLen: 11,
  },
  {
    code: "BN",
    name: "Brunei",
    dialCode: "+673",
    flag: "🇧🇳",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "BG",
    name: "Bulgaria",
    dialCode: "+359",
    flag: "🇧🇬",
    minLen: 8,
    maxLen: 9,
  },
  {
    code: "BF",
    name: "Burkina Faso",
    dialCode: "+226",
    flag: "🇧🇫",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "BI",
    name: "Burundi",
    dialCode: "+257",
    flag: "🇧🇮",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "CV",
    name: "Cabo Verde",
    dialCode: "+238",
    flag: "🇨🇻",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "KH",
    name: "Cambodia",
    dialCode: "+855",
    flag: "🇰🇭",
    minLen: 8,
    maxLen: 9,
  },
  {
    code: "CM",
    name: "Cameroon",
    dialCode: "+237",
    flag: "🇨🇲",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "CA",
    name: "Canada",
    dialCode: "+1",
    flag: "🇨🇦",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "CF",
    name: "Central African Republic",
    dialCode: "+236",
    flag: "🇨🇫",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "TD",
    name: "Chad",
    dialCode: "+235",
    flag: "🇹🇩",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "CL",
    name: "Chile",
    dialCode: "+56",
    flag: "🇨🇱",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "CN",
    name: "China",
    dialCode: "+86",
    flag: "🇨🇳",
    minLen: 11,
    maxLen: 11,
  },
  {
    code: "CO",
    name: "Colombia",
    dialCode: "+57",
    flag: "🇨🇴",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "KM",
    name: "Comoros",
    dialCode: "+269",
    flag: "🇰🇲",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "CG",
    name: "Congo",
    dialCode: "+242",
    flag: "🇨🇬",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "CR",
    name: "Costa Rica",
    dialCode: "+506",
    flag: "🇨🇷",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "HR",
    name: "Croatia",
    dialCode: "+385",
    flag: "🇭🇷",
    minLen: 8,
    maxLen: 9,
  },
  {
    code: "CU",
    name: "Cuba",
    dialCode: "+53",
    flag: "🇨🇺",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "CY",
    name: "Cyprus",
    dialCode: "+357",
    flag: "🇨🇾",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "CZ",
    name: "Czech Republic",
    dialCode: "+420",
    flag: "🇨🇿",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "CD",
    name: "DR Congo",
    dialCode: "+243",
    flag: "🇨🇩",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "DK",
    name: "Denmark",
    dialCode: "+45",
    flag: "🇩🇰",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "DJ",
    name: "Djibouti",
    dialCode: "+253",
    flag: "🇩🇯",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "DM",
    name: "Dominica",
    dialCode: "+1767",
    flag: "🇩🇲",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "DO",
    name: "Dominican Republic",
    dialCode: "+1809",
    flag: "🇩🇴",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "EC",
    name: "Ecuador",
    dialCode: "+593",
    flag: "🇪🇨",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "EG",
    name: "Egypt",
    dialCode: "+20",
    flag: "🇪🇬",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "SV",
    name: "El Salvador",
    dialCode: "+503",
    flag: "🇸🇻",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    dialCode: "+240",
    flag: "🇬🇶",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "ER",
    name: "Eritrea",
    dialCode: "+291",
    flag: "🇪🇷",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "EE",
    name: "Estonia",
    dialCode: "+372",
    flag: "🇪🇪",
    minLen: 7,
    maxLen: 8,
  },
  {
    code: "SZ",
    name: "Eswatini",
    dialCode: "+268",
    flag: "🇸🇿",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "ET",
    name: "Ethiopia",
    dialCode: "+251",
    flag: "🇪🇹",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "FJ",
    name: "Fiji",
    dialCode: "+679",
    flag: "🇫🇯",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "FI",
    name: "Finland",
    dialCode: "+358",
    flag: "🇫🇮",
    minLen: 9,
    maxLen: 10,
  },
  {
    code: "FR",
    name: "France",
    dialCode: "+33",
    flag: "🇫🇷",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "GA",
    name: "Gabon",
    dialCode: "+241",
    flag: "🇬🇦",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "GM",
    name: "Gambia",
    dialCode: "+220",
    flag: "🇬🇲",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "GE",
    name: "Georgia",
    dialCode: "+995",
    flag: "🇬🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "DE",
    name: "Germany",
    dialCode: "+49",
    flag: "🇩🇪",
    minLen: 10,
    maxLen: 11,
  },
  {
    code: "GH",
    name: "Ghana",
    dialCode: "+233",
    flag: "🇬🇭",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "GR",
    name: "Greece",
    dialCode: "+30",
    flag: "🇬🇷",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "GD",
    name: "Grenada",
    dialCode: "+1473",
    flag: "🇬🇩",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "GT",
    name: "Guatemala",
    dialCode: "+502",
    flag: "🇬🇹",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "GN",
    name: "Guinea",
    dialCode: "+224",
    flag: "🇬🇳",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    dialCode: "+245",
    flag: "🇬🇼",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "GY",
    name: "Guyana",
    dialCode: "+592",
    flag: "🇬🇾",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "HT",
    name: "Haiti",
    dialCode: "+509",
    flag: "🇭🇹",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "HN",
    name: "Honduras",
    dialCode: "+504",
    flag: "🇭🇳",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "HU",
    name: "Hungary",
    dialCode: "+36",
    flag: "🇭🇺",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "IS",
    name: "Iceland",
    dialCode: "+354",
    flag: "🇮🇸",
    minLen: 7,
    maxLen: 9,
  },
  {
    code: "IN",
    name: "India",
    dialCode: "+91",
    flag: "🇮🇳",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "ID",
    name: "Indonesia",
    dialCode: "+62",
    flag: "🇮🇩",
    minLen: 9,
    maxLen: 12,
  },
  {
    code: "IR",
    name: "Iran",
    dialCode: "+98",
    flag: "🇮🇷",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "IQ",
    name: "Iraq",
    dialCode: "+964",
    flag: "🇮🇶",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "IE",
    name: "Ireland",
    dialCode: "+353",
    flag: "🇮🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "IL",
    name: "Israel",
    dialCode: "+972",
    flag: "🇮🇱",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "IT",
    name: "Italy",
    dialCode: "+39",
    flag: "🇮🇹",
    minLen: 9,
    maxLen: 11,
  },
  {
    code: "JM",
    name: "Jamaica",
    dialCode: "+1876",
    flag: "🇯🇲",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "JP",
    name: "Japan",
    dialCode: "+81",
    flag: "🇯🇵",
    minLen: 10,
    maxLen: 11,
  },
  {
    code: "JO",
    name: "Jordan",
    dialCode: "+962",
    flag: "🇯🇴",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    dialCode: "+7",
    flag: "🇰🇿",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "KE",
    name: "Kenya",
    dialCode: "+254",
    flag: "🇰🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "KI",
    name: "Kiribati",
    dialCode: "+686",
    flag: "🇰🇮",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "KW",
    name: "Kuwait",
    dialCode: "+965",
    flag: "🇰🇼",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    dialCode: "+996",
    flag: "🇰🇬",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "LA",
    name: "Laos",
    dialCode: "+856",
    flag: "🇱🇦",
    minLen: 9,
    maxLen: 10,
  },
  {
    code: "LV",
    name: "Latvia",
    dialCode: "+371",
    flag: "🇱🇻",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "LB",
    name: "Lebanon",
    dialCode: "+961",
    flag: "🇱🇧",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "LS",
    name: "Lesotho",
    dialCode: "+266",
    flag: "🇱🇸",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "LR",
    name: "Liberia",
    dialCode: "+231",
    flag: "🇱🇷",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "LY",
    name: "Libya",
    dialCode: "+218",
    flag: "🇱🇾",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "LI",
    name: "Liechtenstein",
    dialCode: "+423",
    flag: "🇱🇮",
    minLen: 7,
    maxLen: 9,
  },
  {
    code: "LT",
    name: "Lithuania",
    dialCode: "+370",
    flag: "🇱🇹",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "LU",
    name: "Luxembourg",
    dialCode: "+352",
    flag: "🇱🇺",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "MG",
    name: "Madagascar",
    dialCode: "+261",
    flag: "🇲🇬",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "MW",
    name: "Malawi",
    dialCode: "+265",
    flag: "🇲🇼",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "MY",
    name: "Malaysia",
    dialCode: "+60",
    flag: "🇲🇾",
    minLen: 9,
    maxLen: 10,
  },
  {
    code: "MV",
    name: "Maldives",
    dialCode: "+960",
    flag: "🇲🇻",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "ML",
    name: "Mali",
    dialCode: "+223",
    flag: "🇲🇱",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "MT",
    name: "Malta",
    dialCode: "+356",
    flag: "🇲🇹",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "MH",
    name: "Marshall Islands",
    dialCode: "+692",
    flag: "🇲🇭",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "MR",
    name: "Mauritania",
    dialCode: "+222",
    flag: "🇲🇷",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "MU",
    name: "Mauritius",
    dialCode: "+230",
    flag: "🇲🇺",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "MX",
    name: "Mexico",
    dialCode: "+52",
    flag: "🇲🇽",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "FM",
    name: "Micronesia",
    dialCode: "+691",
    flag: "🇫🇲",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "MD",
    name: "Moldova",
    dialCode: "+373",
    flag: "🇲🇩",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "MC",
    name: "Monaco",
    dialCode: "+377",
    flag: "🇲🇨",
    minLen: 8,
    maxLen: 9,
  },
  {
    code: "MN",
    name: "Mongolia",
    dialCode: "+976",
    flag: "🇲🇳",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "ME",
    name: "Montenegro",
    dialCode: "+382",
    flag: "🇲🇪",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "MA",
    name: "Morocco",
    dialCode: "+212",
    flag: "🇲🇦",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "MZ",
    name: "Mozambique",
    dialCode: "+258",
    flag: "🇲🇿",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "MM",
    name: "Myanmar",
    dialCode: "+95",
    flag: "🇲🇲",
    minLen: 9,
    maxLen: 10,
  },
  {
    code: "NA",
    name: "Namibia",
    dialCode: "+264",
    flag: "🇳🇦",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "NR",
    name: "Nauru",
    dialCode: "+674",
    flag: "🇳🇷",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "NP",
    name: "Nepal",
    dialCode: "+977",
    flag: "🇳🇵",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "NL",
    name: "Netherlands",
    dialCode: "+31",
    flag: "🇳🇱",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "NZ",
    name: "New Zealand",
    dialCode: "+64",
    flag: "🇳🇿",
    minLen: 8,
    maxLen: 10,
  },
  {
    code: "NI",
    name: "Nicaragua",
    dialCode: "+505",
    flag: "🇳🇮",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "NE",
    name: "Niger",
    dialCode: "+227",
    flag: "🇳🇪",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "NG",
    name: "Nigeria",
    dialCode: "+234",
    flag: "🇳🇬",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "NO",
    name: "Norway",
    dialCode: "+47",
    flag: "🇳🇴",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "OM",
    name: "Oman",
    dialCode: "+968",
    flag: "🇴🇲",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "PW",
    name: "Palau",
    dialCode: "+680",
    flag: "🇵🇼",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "PA",
    name: "Panama",
    dialCode: "+507",
    flag: "🇵🇦",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    dialCode: "+675",
    flag: "🇵🇬",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "PY",
    name: "Paraguay",
    dialCode: "+595",
    flag: "🇵🇾",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "PE",
    name: "Peru",
    dialCode: "+51",
    flag: "🇵🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "PH",
    name: "Philippines",
    dialCode: "+63",
    flag: "🇵🇭",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "PL",
    name: "Poland",
    dialCode: "+48",
    flag: "🇵🇱",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "PT",
    name: "Portugal",
    dialCode: "+351",
    flag: "🇵🇹",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "QA",
    name: "Qatar",
    dialCode: "+974",
    flag: "🇶🇦",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "RO",
    name: "Romania",
    dialCode: "+40",
    flag: "🇷🇴",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "RU",
    name: "Russia",
    dialCode: "+7",
    flag: "🇷🇺",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "RW",
    name: "Rwanda",
    dialCode: "+250",
    flag: "🇷🇼",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    dialCode: "+1869",
    flag: "🇰🇳",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "LC",
    name: "Saint Lucia",
    dialCode: "+1758",
    flag: "🇱🇨",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "VC",
    name: "Saint Vincent",
    dialCode: "+1784",
    flag: "🇻🇨",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "WS",
    name: "Samoa",
    dialCode: "+685",
    flag: "🇼🇸",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "SM",
    name: "San Marino",
    dialCode: "+378",
    flag: "🇸🇲",
    minLen: 8,
    maxLen: 10,
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    dialCode: "+239",
    flag: "🇸🇹",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    dialCode: "+966",
    flag: "🇸🇦",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "SN",
    name: "Senegal",
    dialCode: "+221",
    flag: "🇸🇳",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "RS",
    name: "Serbia",
    dialCode: "+381",
    flag: "🇷🇸",
    minLen: 8,
    maxLen: 9,
  },
  {
    code: "SC",
    name: "Seychelles",
    dialCode: "+248",
    flag: "🇸🇨",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "SL",
    name: "Sierra Leone",
    dialCode: "+232",
    flag: "🇸🇱",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "SG",
    name: "Singapore",
    dialCode: "+65",
    flag: "🇸🇬",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "SK",
    name: "Slovakia",
    dialCode: "+421",
    flag: "🇸🇰",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "SI",
    name: "Slovenia",
    dialCode: "+386",
    flag: "🇸🇮",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "SB",
    name: "Solomon Islands",
    dialCode: "+677",
    flag: "🇸🇧",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "SO",
    name: "Somalia",
    dialCode: "+252",
    flag: "🇸🇴",
    minLen: 8,
    maxLen: 9,
  },
  {
    code: "ZA",
    name: "South Africa",
    dialCode: "+27",
    flag: "🇿🇦",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "SS",
    name: "South Sudan",
    dialCode: "+211",
    flag: "🇸🇸",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "ES",
    name: "Spain",
    dialCode: "+34",
    flag: "🇪🇸",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "LK",
    name: "Sri Lanka",
    dialCode: "+94",
    flag: "🇱🇰",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "SD",
    name: "Sudan",
    dialCode: "+249",
    flag: "🇸🇩",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "SR",
    name: "Suriname",
    dialCode: "+597",
    flag: "🇸🇷",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "SE",
    name: "Sweden",
    dialCode: "+46",
    flag: "🇸🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "CH",
    name: "Switzerland",
    dialCode: "+41",
    flag: "🇨🇭",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "SY",
    name: "Syria",
    dialCode: "+963",
    flag: "🇸🇾",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "TW",
    name: "Taiwan",
    dialCode: "+886",
    flag: "🇹🇼",
    minLen: 9,
    maxLen: 10,
  },
  {
    code: "TJ",
    name: "Tajikistan",
    dialCode: "+992",
    flag: "🇹🇯",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "TZ",
    name: "Tanzania",
    dialCode: "+255",
    flag: "🇹🇿",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "TH",
    name: "Thailand",
    dialCode: "+66",
    flag: "🇹🇭",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "TL",
    name: "Timor-Leste",
    dialCode: "+670",
    flag: "🇹🇱",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "TG",
    name: "Togo",
    dialCode: "+228",
    flag: "🇹🇬",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "TO",
    name: "Tonga",
    dialCode: "+676",
    flag: "🇹🇴",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    dialCode: "+1868",
    flag: "🇹🇹",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "TN",
    name: "Tunisia",
    dialCode: "+216",
    flag: "🇹🇳",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "TR",
    name: "Turkey",
    dialCode: "+90",
    flag: "🇹🇷",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "TM",
    name: "Turkmenistan",
    dialCode: "+993",
    flag: "🇹🇲",
    minLen: 8,
    maxLen: 8,
  },
  {
    code: "TV",
    name: "Tuvalu",
    dialCode: "+688",
    flag: "🇹🇻",
    minLen: 6,
    maxLen: 6,
  },
  {
    code: "UG",
    name: "Uganda",
    dialCode: "+256",
    flag: "🇺🇬",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "UA",
    name: "Ukraine",
    dialCode: "+380",
    flag: "🇺🇦",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    dialCode: "+971",
    flag: "🇦🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "GB",
    name: "United Kingdom",
    dialCode: "+44",
    flag: "🇬🇧",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "US",
    name: "United States",
    dialCode: "+1",
    flag: "🇺🇸",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "UY",
    name: "Uruguay",
    dialCode: "+598",
    flag: "🇺🇾",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    dialCode: "+998",
    flag: "🇺🇿",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "VU",
    name: "Vanuatu",
    dialCode: "+678",
    flag: "🇻🇺",
    minLen: 7,
    maxLen: 7,
  },
  {
    code: "VE",
    name: "Venezuela",
    dialCode: "+58",
    flag: "🇻🇪",
    minLen: 10,
    maxLen: 10,
  },
  {
    code: "VN",
    name: "Vietnam",
    dialCode: "+84",
    flag: "🇻🇳",
    minLen: 9,
    maxLen: 10,
  },
  {
    code: "YE",
    name: "Yemen",
    dialCode: "+967",
    flag: "🇾🇪",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "ZM",
    name: "Zambia",
    dialCode: "+260",
    flag: "🇿🇲",
    minLen: 9,
    maxLen: 9,
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    dialCode: "+263",
    flag: "🇿🇼",
    minLen: 9,
    maxLen: 9,
  },
];

// Default country: Pakistan
const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.code === "PK");

export function PhoneInput({
  name,
  value,
  onChange,
  error,
  placeholder = "3XXXXXXXXX",
}) {
  const [selectedCountry, setSelectedCountry] = useState(DEFAULT_COUNTRY);
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [search, setSearch] = useState("");
  const dropdownRef = useRef(null);
  const searchRef = useRef(null);

  const filteredCountries = COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.dialCode.includes(search),
  );

  // Close dropdown on outside click
  useEffect(() => {
    const handleClick = (e) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
        setDropdownOpen(false);
        setSearch("");
      }
    };
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  // Focus search on open
  useEffect(() => {
    if (dropdownOpen && searchRef.current) {
      setTimeout(() => searchRef.current?.focus(), 50);
    }
  }, [dropdownOpen]);

  const handleCountrySelect = (country) => {
    setSelectedCountry(country);
    setDropdownOpen(false);
    setSearch("");
    // Clear the number when country changes
    onChange({ target: { name, value: "", _country: country } });
  };

  const handleNumberChange = (e) => {
    const digitsOnly = e.target.value
      .replace(/\D/g, "")
      .slice(0, selectedCountry.maxLen);
    onChange({
      target: {
        name,
        value: digitsOnly,
        _country: selectedCountry,
      },
    });
  };

  return (
    <div className={`phone-input-wrapper ${error ? "phone-input-error" : ""}`}>
      {/* Country Selector */}
      <div className="phone-country-selector" ref={dropdownRef}>
        <button
          type="button"
          className="phone-country-btn"
          onClick={() => setDropdownOpen((prev) => !prev)}
        >
          <span className="phone-flag">{selectedCountry.flag}</span>
          <span className="phone-dial">{selectedCountry.dialCode}</span>
          <span className="phone-chevron">{dropdownOpen ? "▲" : "▼"}</span>
        </button>

        {dropdownOpen && (
          <div className="phone-dropdown">
            <div className="phone-search-wrap">
              <input
                ref={searchRef}
                type="text"
                className="phone-search"
                placeholder="Search country..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <ul className="phone-country-list">
              {filteredCountries.length === 0 ? (
                <li className="phone-no-results">No results found</li>
              ) : (
                filteredCountries.map((country) => (
                  <li
                    key={country.code}
                    className={`phone-country-item ${selectedCountry.code === country.code ? "selected" : ""}`}
                    onClick={() => handleCountrySelect(country)}
                  >
                    <span className="phone-flag">{country.flag}</span>
                    <span className="phone-country-name">{country.name}</span>
                    <span className="phone-country-dial">
                      {country.dialCode}
                    </span>
                  </li>
                ))
              )}
            </ul>
          </div>
        )}
      </div>

      {/* Number Input */}
      <input
        type="text"
        className="phone-number-input"
        name={name}
        value={value}
        onChange={handleNumberChange}
        placeholder={`${selectedCountry.minLen === selectedCountry.maxLen ? selectedCountry.maxLen : selectedCountry.minLen + "-" + selectedCountry.maxLen} digits`}
        maxLength={selectedCountry.maxLen}
        inputMode="numeric"
      />
    </div>
  );
}

// Export country list and default for use in validation
export { COUNTRIES, DEFAULT_COUNTRY };
